language: java

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

before_install:
  - |
    if [ "$TRAVIS_JDK_VERSION" == "openjdk7" ]; then
      sudo wget "https://bouncycastle.org/download/bcprov-jdk15on-159.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-jdk15on-159.jar"
      sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
      echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
    fi

install: mvn install -Dgpg.skip=true -DskipTests
