name: Maven Verify

on:
  pull_request:
    branches: [ master ]


jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Run Maven Verify
      env:
        CRD_KEY: ${{secrets.CRD_KEY}}
        CRD_SECRET: ${{secrets.CRD_SECRET}}
      run: mvn clean verify -Dgpg.skip=true